### ISSUE TITLE
Bug: 2023-10-15を選択すると例外でページが真っ白になる

### ISSUE THREAD

**Issue by zabrox** [zabrox/wefly#64]
stack traceは以下。
```
track.jsx:90 Uncaught RangeError: Maximum call stack size exceeded
    at Track.maxAltitude (track.jsx:90:38)
    at Object.display (tracklistheader.jsx:63:39)
    at TrackCell (tracklistbody.jsx:13:54)
    at renderWithHooks (chunk-GYWC62UC.js?v=526cad96:12171:26)
    at mountIndeterminateComponent (chunk-GYWC62UC.js?v=526cad96:14921:21)
    at beginWork (chunk-GYWC62UC.js?v=526cad96:15902:22)
    at HTMLUnknownElement.callCallback2 (chunk-GYWC62UC.js?v=526cad96:3674:22)
    at Object.invokeGuardedCallbackDev (chunk-GYWC62UC.js?v=526cad96:3699:24)
    at invokeGuardedCallback (chunk-GYWC62UC.js?v=526cad96:3733:39)
    at beginWork$1 (chunk-GYWC62UC.js?v=526cad96:19761:15)
maxAltitude @ track.jsx:90
display @ tracklistheader.jsx:63
TrackCell @ tracklistbody.jsx:13
renderWithHooks @ chunk-GYWC62UC.js?v=526cad96:12171
mountIndeterminateComponent @ chunk-GYWC62UC.js?v=526cad96:14921
beginWork @ chunk-GYWC62UC.js?v=526cad96:15902
callCallback2 @ chunk-GYWC62UC.js?v=526cad96:3674
invokeGuardedCallbackDev @ chunk-GYWC62UC.js?v=526cad96:3699
invokeGuardedCallback @ chunk-GYWC62UC.js?v=526cad96:3733
beginWork$1 @ chunk-GYWC62UC.js?v=526cad96:19761
performUnitOfWork @ chunk-GYWC62UC.js?v=526cad96:19194
workLoopSync @ chunk-GYWC62UC.js?v=526cad96:19133
renderRootSync @ chunk-GYWC62UC.js?v=526cad96:19112
performConcurrentWorkOnRoot @ chunk-GYWC62UC.js?v=526cad96:18674
workLoop @ chunk-GYWC62UC.js?v=526cad96:197
flushWork @ chunk-GYWC62UC.js?v=526cad96:176
performWorkUntilDeadline @ chunk-GYWC62UC.js?v=526cad96:384
他 14 件のフレームを表示
一部表示
track.jsx:90 Uncaught RangeError: Maximum call stack size exceeded
    at Track.maxAltitude (track.jsx:90:38)
    at Object.display (tracklistheader.jsx:63:39)
    at TrackCell (tracklistbody.jsx:13:54)
    at renderWithHooks (chunk-GYWC62UC.js?v=526cad96:12171:26)
    at mountIndeterminateComponent (chunk-GYWC62UC.js?v=526cad96:14921:21)
    at beginWork (chunk-GYWC62UC.js?v=526cad96:15902:22)
    at HTMLUnknownElement.callCallback2 (chunk-GYWC62UC.js?v=526cad96:3674:22)
    at Object.invokeGuardedCallbackDev (chunk-GYWC62UC.js?v=526cad96:3699:24)
    at invokeGuardedCallback (chunk-GYWC62UC.js?v=526cad96:3733:39)
    at beginWork$1 (chunk-GYWC62UC.js?v=526cad96:19761:15)
maxAltitude @ track.jsx:90
display @ tracklistheader.jsx:63
TrackCell @ tracklistbody.jsx:13
renderWithHooks @ chunk-GYWC62UC.js?v=526cad96:12171
mountIndeterminateComponent @ chunk-GYWC62UC.js?v=526cad96:14921
beginWork @ chunk-GYWC62UC.js?v=526cad96:15902
callCallback2 @ chunk-GYWC62UC.js?v=526cad96:3674
invokeGuardedCallbackDev @ chunk-GYWC62UC.js?v=526cad96:3699
invokeGuardedCallback @ chunk-GYWC62UC.js?v=526cad96:3733
beginWork$1 @ chunk-GYWC62UC.js?v=526cad96:19761
performUnitOfWork @ chunk-GYWC62UC.js?v=526cad96:19194
workLoopSync @ chunk-GYWC62UC.js?v=526cad96:19133
renderRootSync @ chunk-GYWC62UC.js?v=526cad96:19112
recoverFromConcurrentError @ chunk-GYWC62UC.js?v=526cad96:18732
performConcurrentWorkOnRoot @ chunk-GYWC62UC.js?v=526cad96:18680
workLoop @ chunk-GYWC62UC.js?v=526cad96:197
flushWork @ chunk-GYWC62UC.js?v=526cad96:176
performWorkUntilDeadline @ chunk-GYWC62UC.js?v=526cad96:384
他 15 件のフレームを表示
一部表示
console.js:213 The above error occurred in the <TrackCell> component:

    at TrackCell (http://localhost:3000/src/tracklistbody.jsx:28:3)
    at tr
    at http://localhost:3000/node_modules/.vite/deps/chunk-7RIW3DLB.js?v=526cad96:3584:50
    at TableRow2 (http://localhost:3000/node_modules/.vite/deps/@mui_material.js?v=526cad96:20263:17)
    at tbody
    at http://localhost:3000/node_modules/.vite/deps/chunk-7RIW3DLB.js?v=526cad96:3584:50
    at TableBody2 (http://localhost:3000/node_modules/.vite/deps/@mui_material.js?v=526cad96:18962:17)
    at TrackListBody (http://localhost:3000/src/tracklistbody.jsx:54:3)
    at table
    at http://localhost:3000/node_modules/.vite/deps/chunk-7RIW3DLB.js?v=526cad96:3584:50
    at Table2 (http://localhost:3000/node_modules/.vite/deps/@mui_material.js?v=526cad96:18829:17)
    at div
    at http://localhost:3000/node_modules/.vite/deps/chunk-7RIW3DLB.js?v=526cad96:3584:50
    at TableContainer2 (http://localhost:3000/node_modules/.vite/deps/@mui_material.js?v=526cad96:19268:17)
    at div
    at ControlPanel (http://localhost:3000/src/controlpanel.jsx?t=1703606269471:25:3)
    at div
    at LocalizationProvider2 (http://localhost:3000/node_modules/.vite/deps/@mui_x-date-pickers.js?v=526cad96:113:17)
    at World (http://localhost:3000/src/world.jsx?t=1703606269471:203:36)

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://reactjs.org/link/error-boundaries to learn more about error boundaries.
overrideMethod @ console.js:213
logCapturedError @ chunk-GYWC62UC.js?v=526cad96:14036
update.callback @ chunk-GYWC62UC.js?v=526cad96:14056
callCallback @ chunk-GYWC62UC.js?v=526cad96:10511
commitUpdateQueue @ chunk-GYWC62UC.js?v=526cad96:10528
commitLayoutEffectOnFiber @ chunk-GYWC62UC.js?v=526cad96:17083
commitLayoutMountEffects_complete @ chunk-GYWC62UC.js?v=526cad96:17976
commitLayoutEffects_begin @ chunk-GYWC62UC.js?v=526cad96:17965
commitLayoutEffects @ chunk-GYWC62UC.js?v=526cad96:17916
commitRootImpl @ chunk-GYWC62UC.js?v=526cad96:19349
commitRoot @ chunk-GYWC62UC.js?v=526cad96:19273
finishConcurrentRender @ chunk-GYWC62UC.js?v=526cad96:18756
performConcurrentWorkOnRoot @ chunk-GYWC62UC.js?v=526cad96:18714
workLoop @ chunk-GYWC62UC.js?v=526cad96:197
flushWork @ chunk-GYWC62UC.js?v=526cad96:176
performWorkUntilDeadline @ chunk-GYWC62UC.js?v=526cad96:384
他 16 件のフレームを表示
一部表示
chunk-GYWC62UC.js?v=526cad96:19409 Uncaught RangeError: Maximum call stack size exceeded
    at Track.maxAltitude (track.jsx:90:38)
    at Object.display (tracklistheader.jsx:63:39)
    at TrackCell (tracklistbody.jsx:13:54)
    at renderWithHooks (chunk-GYWC62UC.js?v=526cad96:12171:26)
    at mountIndeterminateComponent (chunk-GYWC62UC.js?v=526cad96:14921:21)
    at beginWork (chunk-GYWC62UC.js?v=526cad96:15902:22)
    at beginWork$1 (chunk-GYWC62UC.js?v=526cad96:19749:22)
    at performUnitOfWork (chunk-GYWC62UC.js?v=526cad96:19194:20)
    at workLoopSync (chunk-GYWC62UC.js?v=526cad96:19133:13)
    at renderRootSync (chunk-GYWC62UC.js?v=526cad96:19112:15)
maxAltitude @ track.jsx:90
display @ tracklistheader.jsx:63
TrackCell @ tracklistbody.jsx:13
renderWithHooks @ chunk-GYWC62UC.js?v=526cad96:12171
mountIndeterminateComponent @ chunk-GYWC62UC.js?v=526cad96:14921
beginWork @ chunk-GYWC62UC.js?v=526cad96:15902
beginWork$1 @ chunk-GYWC62UC.js?v=526cad96:19749
performUnitOfWork @ chunk-GYWC62UC.js?v=526cad96:19194
workLoopSync @ chunk-GYWC62UC.js?v=526cad96:19133
renderRootSync @ chunk-GYWC62UC.js?v=526cad96:19112
recoverFromConcurrentError @ chunk-GYWC62UC.js?v=526cad96:18732
performConcurrentWorkOnRoot @ chunk-GYWC62UC.js?v=526cad96:18680
workLoop @ chunk-GYWC62UC.js?v=526cad96:197
flushWork @ chunk-GYWC62UC.js?v=526cad96:176
performWorkUntilDeadline @ chunk-GYWC62UC.js?v=526cad96:384
他 12 件のフレームを表示
一部表示
world.jsx:48 Uncaught (in promise) RangeError: Maximum call stack size exceeded
    at world.jsx:48:44
    at Array.forEach (<anonymous>)
    at zoomToTracks (world.jsx:48:16)
    at loadTracks (world.jsx:74:5)
```

**Comment by zabrox** [comment]
この日以外に発生していない。
非常に稀なケースだと思うので、再発したら再度Openする。
