### ISSUE TITLE
Bug: 日付選択すると例外が出てtrack一覧が表示されない

### ISSUE THREAD

**Issue by zabrox** [zabrox/wefly#68]
Uncaught (in promise) TypeError: e.map is not a function
    at e4 (index-690a6c8a.js:152:4491)
    at Yx (index-690a6c8a.js:152:4216)

**Comment by zabrox** [comment]
原因はわからないが、parseAllTracksをPromise.all対応したことに起因しているよう。
Promise.allはそこまで効果がなさそうなので、元のコードに戻す。

**Comment by zabrox** [comment]
全然原因が違った。
問題はCloud Runで動作しているapi server。
api serverからのJSON応答が途中で途切れて、中途半端なJSONが返ってきている。
ローカルのdocker環境で動かしたときには特に問題ないので、CloudRunの何らかの制約に引っかかっているのだと思う。

**Comment by zabrox** [comment]
現状ではfile.createReadStreamを使ってStreamingしているが、途中でstreamが切れてしまっているよう。
何に起因するのかは不明だが、streamを廃止してfileのGCSからのダウンロード、展開、レスポンス応答をシーケンシャルに行うように書き換えたところ問題なく動作するようになった。
